name: 'enterprise_etl_pipeline'
version: '1.0.0'
config-version: 2

profile: 'snowflake_production'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  enterprise_etl_pipeline:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: analytics
      finance:
        +materialized: table
      product:
        +materialized: table

vars:
  start_date: '2020-01-01'

